# Head Pose Image Database

http://www-prima.inrialpes.fr/perso/Gourier/Faces/HPDatabase.html

## このデータベースを利用する目的：

さまざまな顔の向きで顔を検出できるかどうかを評価する。

各pitch, yaw の組み合わせに対して、３０枚の画像があり、
顔向きごとの検出率を評価できる。

## 評価上の注意点：

- 背景がフラットな画像になっているので、背景が込み入っている時の検出率を評価できない。
- 被験者が欧米人に偏っている。
- 照明条件の多様性がない。
- 表情の変化が少ない（口を開けたりはしていない）


In [1]:
%matplotlib inline
import pandas as pd

In [ ]:

import glob
dataset = "headPose"
names = glob.glob("headPose/Person*/*.jpg")

In [ ]:
names.sort()
import HaarFrontal as faceDetector
faceDetector.processDatabase(dataset, names)

/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:2957: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)


[[ 47  30 160 160]]
<type 'numpy.ndarray'>
[[ 71  20 173 173]]
<type 'numpy.ndarray'>
[[ 25  52 134 134]]
<type 'numpy.ndarray'>
[[ 32  19 199 199]]
<type 'numpy.ndarray'>
[[ 21  65 118 118]]
<type 'numpy.ndarray'>
[[ 20  24 199 199]]
<type 'numpy.ndarray'>
[[ 10  68 122 122]]
<type 'numpy.ndarray'>
[[ 20  36 181 181]]
<type 'numpy.ndarray'>
[[ 30  44 157 157]]
<type 'numpy.ndarray'>
[[ 45  24 190 190]]
<type 'numpy.ndarray'>
[[ 25  57 129 129]]
<type 'numpy.ndarray'>
[[ 30  31 181 181]]
<type 'numpy.ndarray'>
[[ 14  63 118 118]]
<type 'numpy.ndarray'>
[[ 19  26 190 190]]
<type 'numpy.ndarray'>
[[ 66  35 162 162]]
<type 'numpy.ndarray'>
[[ 88  26 174 174]]
<type 'numpy.ndarray'>
[[ 27  28 169 169]]
<type 'numpy.ndarray'>
[[ 50  20 196 196]]
<type 'numpy.ndarray'>
[[ 21  30 165 165]]
<type 'numpy.ndarray'>
[[ 48  23 185 185]]
<type 'numpy.ndarray'>
[[ 59  16 167 167]]
<type 'numpy.ndarray'>
[[ 95  20 150 150]]
<type 'numpy.ndarray'>
[[ 46  23 149 149]]
<type 'numpy.ndarray'>
[[ 64  12 1

[[ 84  26 161 161]]
<type 'numpy.ndarray'>
[[103  14 179 179]]
<type 'numpy.ndarray'>
[[ 64  31 142 142]]
<type 'numpy.ndarray'>
[[ 87  20 159 159]]
<type 'numpy.ndarray'>
[[ 58  35 134 134]]
<type 'numpy.ndarray'>
[[ 72  20 165 165]]
<type 'numpy.ndarray'>
[[ 43  40 125 125]]
<type 'numpy.ndarray'>
[[ 49  19 171 171]]
<type 'numpy.ndarray'>
[[ 76  25 143 143]]
<type 'numpy.ndarray'>
[[102  19 147 147]]
<type 'numpy.ndarray'>
[[ 66  30 132 132]]
<type 'numpy.ndarray'>
[[ 83  15 162 162]]
<type 'numpy.ndarray'>
[[ 48  32 131 131]]
<type 'numpy.ndarray'>
[[ 60  13 171 171]]
<type 'numpy.ndarray'>
[[ 86   8 134 134]]
<type 'numpy.ndarray'>
[[122  14 123 123]]
<type 'numpy.ndarray'>
[[ 78  10 132 132]]
<type 'numpy.ndarray'>
[[112  12 130 130]]
<type 'numpy.ndarray'>
[[ 61   9 135 135]]
<type 'numpy.ndarray'>
[[ 83   8 145 145]]
<type 'numpy.ndarray'>
[[ 62  12 131 131]]
<type 'numpy.ndarray'>
[[ 94   7 142 142]]
<type 'numpy.ndarray'>
[[ 52  11 141 141]]
<type 'numpy.ndarray'>
[[ 80  10 1

[[ 69  49 151 151]]
<type 'numpy.ndarray'>
[[ 90  36 171 171]]
<type 'numpy.ndarray'>
[[ 66  50 136 136]]
<type 'numpy.ndarray'>
[[ 75  32 169 169]]
<type 'numpy.ndarray'>
[[ 51  54 131 131]]
<type 'numpy.ndarray'>
[[ 60  30 172 172]]
<type 'numpy.ndarray'>
[[ 89  35 132 132]]
<type 'numpy.ndarray'>
[[ 92  19 170 170]]
<type 'numpy.ndarray'>
[[ 68  35 136 136]]
<type 'numpy.ndarray'>
[[ 72  17 175 175]]
<type 'numpy.ndarray'>
[[ 79  22 134 134]]
<type 'numpy.ndarray'>
[[ 93   9 159 159]]
<type 'numpy.ndarray'>
[[ 65  91 138 138]]
<type 'numpy.ndarray'>
[[ 66  67 184 184]]
<type 'numpy.ndarray'>
[[ 30  96 116 116]]
<type 'numpy.ndarray'>
[[ 40  83 152 152]]
<type 'numpy.ndarray'>


# headPose dataset の検出処理後のデータ解析

In [ ]:
import pandas as pd
import readheadPose
df = pd.read_csv("log_headPose_0.csv")

pitches = []
yaws = []
angles = []
for index, rows in df.iterrows():
#    print index, rows["name"]
    pitch, yaw = readheadPose.getAngles(rows["name"])
    pitches.append(float(pitch))    
    yaws.append(float(yaw))    
    angles.append("%s_%s" % (pitch, yaw))

df["angles"] = angles
df["pitch"] = pitches
df["yaws"] = yaws



print df.groupby("num").count()



In [ ]:
print "検出数の分布(比率)"
print df.groupby("num").count()/float(df.shape[0])

In [ ]:
print "検出数のヒストグラム"
ax = df["num"].hist(bins=11)
ax.set_xlabel("number of detections")
ax.set_ylabel("Frequency")


## HaaR Cascade の検出器のついて
haarcascade_frontalface_default.xml
を用いているので、正面向き以外に対しては検出性能に限界がある。


## 検出数の分布を角度の組み合わせごとに集約する

In [ ]:
dfSum = df.groupby("angles").sum();


In [ ]:
dfSum = dfSum.drop("pitch", axis=1);
dfSum = dfSum.drop("yaws", axis=1);
dfSum

In [ ]:
dfMean = df.groupby("angles").mean()
dfMean

In [ ]:
dfMean = dfMean.drop("pitch", axis=1);
dfMean = dfMean.drop("yaws", axis=1);
dfMean

降べきの順に表示させる。
そうすると、どの角度範囲までが検出率が高いのかがわかる。

In [ ]:
dfMean.sort_values("truePositives", ascending=False)

In [ ]:
df["num"].mean()


In [ ]:
print df[df["num"]==0]


pitch　が 90 のデータは検出されていないものが多いことがわかる。

In [ ]:
print df[df["pitch"]==90]

In [ ]:
print df[df["pitch"]==90].groupby("num").count()
print "num 0で表示されたcount だけ未検出だったことがわかる"

In [ ]:
print df[df["num"]==2]
print "検出数が２つ以上あるものは、誤検出を含んでいることがわかる"

In [ ]:
df["truePositives"].hist()
print "顔がひとつしかない画像を入力にしているので、検出された時は１、未検出の時は０になる"

In [ ]:
df.shape


In [ ]:
print df.groupby("truePositives").count()

In [ ]:
df[df["truePositives"]==0]
